security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:

        ROLE_USER:  ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                login_path:          fos_user_security_login
                check_path:          fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /home
                use_forward: false
                require_previous_session: false

            logout:    true
            anonymous:    true
            logout_on_user_change: true
            remember_me:
                secret:   '%secret%'
                lifetime: 20 # 1 week in seconds

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/parent, role: ROLE_PARENT }