<?php

namespace VieEleveBundle\Repository;

/**
 * abonneTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abonneTransportRepository extends \Doctrine\ORM\EntityRepository
{
    public function tri()
    {  $Query = $this->getEntityManager()->createQuery
    ('SELECT M FROM VieEleveBundle:abonneTransport M  ORDER BY M.username ');
        return $Query->getResult();
    }
}
