<?php

namespace VieEleveBundle\Repository;

/**
 * eleveRestauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eleveRestauRepository extends \Doctrine\ORM\EntityRepository
{ public  function  calcul($id)
{
    $q=$this->getEntityManager()->createQuery(
        "update VieEleveBundle:eleveRestau A 
         set A.solde=A.solde-15 where  A.trajet=:id"
    )->
    setParameter('id',$id);
    return $q->getResult();
}
    public function tri()
    {  $Query = $this->getEntityManager()->createQuery
    ('SELECT M FROM VieEleveBundle:eleveRestau M  ORDER BY M.username ');
        return $Query->getResult();
    }

}
