<?php

namespace VieEleveBundle\Repository;
use VieEleveBundle\Entity\menu;
use Doctrine\ORM\Query;

/**
 * menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menuRepository extends \Doctrine\ORM\EntityRepository
{   public function findEntitiesByString($str){
    return $this->getEntityManager()
        ->createQuery(
            'SELECT p
                FROM VieEleveBundle:menu p
                WHERE p.items LIKE :str'
        )
        ->setParameter('str', '%'.$str.'%')
        ->getResult();
}

}
