<?php

namespace VieEleveBundle\Repository;

/**
 * quittanceTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class quittanceTransportRepository extends \Doctrine\ORM\EntityRepository
{  public  function  findBySimulation($id)
{
    $q=$this->getEntityManager()->createQuery(
        "select A from VieEleveBundle:quittanceTransport A 
        where A.eleve_transport = :id "
    )
        ->setParameter('id',$id);
    return $q->getResult();
}
    public  function  findById1()
    {
        $q=$this->getEntityManager()->createQuery(
            "select A from VieEleveBundle:quittanceTransport A 
        where A.id = 1"
        );
        return $q->getResult();
    }

}
